-- Generated by tools/write_build_id.sh from VERSION; DO NOT EDIT.
-- The revision is optional: a tree without git metadata has none to report, and
-- inventing one would be worse than saying so.
local ok, build_id = pcall(require, "wtop.build_id")

return {
    name = "wtop",
    version = "0.1.0",
    revision = ok and type(build_id) == "table" and build_id.revision or nil,
    description = "WaterRun's top — a deep Linux observability TUI",
}
