#!/usr/bin/env python3
"""Generate a CycloneDX 1.5 SBOM for the wtop release artifacts.

Usage: tools/make_sbom.py [--onedir DIR] [--onefile PATH] [--output PATH]

    --onedir   the luainstaller onedir bundle   (default dist/wtop)
    --onefile  the single-file bundle           (default dist/wtop-onefile)

The artifacts are named separately rather than as one root because they are not
one directory: the onedir bundle is a directory and the onefile is a file beside
it.  An earlier version took a single --bundle and looked for both entry points
inside it, so the onefile could never be found -- it is a sibling of the bundle
directory, not a child of it.

A missing artifact is an error, not a smaller document.  This generator used to
take a bundle path that did not exist, find no files in it, and write a complete,
well-formed CycloneDX 1.5 document with three components, a serial number,
licenses and purls -- and no hashes at all, because the hashes were the only part
that needed a file to be there.  It printed "SBOM written" and exited 0, and the
result sat in dist/ looking like release evidence.  An SBOM's whole purpose is to
say which bytes are being shipped, so one without a hash for the artifact cannot
answer the only question it exists to answer, and the failure mode was silent.
That file is the reason this refuses to run rather than degrading.
"""

import argparse
import hashlib
import json
import pathlib
import subprocess
import sys
import typing
import uuid

# The annotations below are spelled with typing.Optional/List/Dict rather than
# `str | None` and `list[...]`.  Both spellings read better, and only one of
# them can run where this project's oldest-libc evidence is produced: the
# manylinux2014 image ships Python 3.6, where `from __future__ import
# annotations` is a SyntaxError and PEP 604 unions are not grammar.  A release
# tool that cannot start in the environment used to verify the oldest supported
# libc is not a release tool for that libc.

LUA_VERSION = "5.5.1"
LUAINSTALLER_VERSION = "1.3.0"
def declared_version(root: pathlib.Path) -> str:
    """The version the project writes down, from the one file that holds it.

    This was a literal here, matching one in src/wtop/version.lua and one in the
    C source.  Three copies of a fact that two user-facing commands print is two
    copies too many, and the SBOM is the document a distributor reads to decide
    what a release contains -- so its version came from the least checkable of
    the three.  An empty or absent VERSION is a hard error rather than a
    fallback: this file is generated by tools/write_build_id.sh from the same
    file, and a generator that cannot find its input is a build error.
    """
    path = root / "VERSION"
    try:
        version = path.read_text(encoding="utf-8").strip()
    except OSError as error:
        print("wtop: cannot read %s: %s" % (path, error), file=sys.stderr)
        raise SystemExit(2)
    if not version:
        print("wtop: %s is empty; it is the only place the version is written"
              % path, file=sys.stderr)
        raise SystemExit(2)
    return version

# The three executables are named exactly once, in `candidates` below.  An
# earlier version kept a separate ARTIFACTS list describing the same three
# files and then never read it, so the native module -- which the list itself
# said was compiled from this project -- appeared in no component at all.  A
# second list of the same facts is a second thing to forget to update, and
# nothing fails when it is stale.
#
# The licence texts are a different kind of shipped file and are handled
# separately below, because being absent means something different: a missing
# executable means the release was never built, while a missing licence text
# means it was built and then described as governed by terms it does not carry.


# Every licence this document declares on a component, and the file inside the
# onedir bundle that has to carry its text.
#
# A licence id in a component says the release is governed by those terms, and
# the only way a re-distributor can comply with them is to read them.  So a
# declaration whose text the release does not carry is a claim with nothing
# behind it -- which is the same defect as hashing nothing, one level up.  This
# document named EUPL-1.2 on both wtop components while shipping neither the
# text nor a reference to it, and it reported success with the Lua MIT text
# taken out of the bundle entirely, because the hashes were the only part that
# needed a file to be there.
#
# Whether a text also reaches the onefile is measured here rather than assumed
# from how the packaging tool works: the onefile carries the Lua and LGPL
# notices inside its own bytes, and it does not carry the project's own licence
# because luainstaller's only supported mechanism for adding a file, --include,
# accepts Lua source and rejects everything else.  Recording that per licence
# is the point.  A gap a distributor can see is a decision they can make; the
# same gap inferred from silence is one they cannot.
LICENCE_TEXTS = (
    ("EUPL-1.2", "LICENSE",
     "the project's own terms"),
    ("MIT", ".luai/licenses/Lua-MIT.txt",
     "the PUC Lua runtime the release links and carries"),
    ("LGPL-3.0-or-later", ".luai/licenses/LGPL-3.0-or-later.txt",
     "the packaging tool the generated launcher derives from"),
)


def git_revision(root: pathlib.Path) -> typing.Optional[str]:
    try:
        return subprocess.run(
            ["git", "-C", str(root), "describe", "--always", "--dirty", "--tags"],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            universal_newlines=True, check=True,
        ).stdout.strip() or None
    except (OSError, subprocess.CalledProcessError):
        return None


def file_hash(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def embeds_verbatim(container: pathlib.Path, payload: pathlib.Path) -> bool:
    """Whether `payload`'s exact bytes appear inside `container`.

    A sentence in the document has to be a fact about the artifacts rather than
    an assumption about how the packaging works.  Whether the onefile carries the
    very same module that the onedir bundle ships, or a copy rebuilt from the
    same source, is exactly the kind of thing a future packaging change would
    alter without anyone editing this file, so it is measured here and the
    wording follows the measurement.
    """
    needle = payload.read_bytes()
    if not needle:
        return False
    overlap = len(needle) - 1
    with container.open("rb") as handle:
        carried = b""
        while True:
            chunk = handle.read(1024 * 1024)
            if not chunk:
                return False
            if needle in carried + chunk:
                return True
            # A payload straddling a chunk boundary would otherwise be missed.
            carried = chunk[-overlap:] if overlap else b""


def component(identifier: str, name: str, version: str, license_id: str,
              description: str, kind: str = "library",
              scope: str = "required",
              hashes=None, properties=None) -> typing.Dict:
    entry = {
        "bom-ref": identifier,
        "type": kind,
        "name": name,
        "version": version,
        "licenses": [{"license": {"id": license_id}}],
        "purl": f"pkg:generic/{name}@{version}",
        "scope": scope,
        "description": description,
    }
    if hashes:
        entry["hashes"] = hashes
    if properties:
        entry["properties"] = properties
    return entry


def licence_properties(record: typing.Dict) -> typing.List[typing.Dict]:
    """Where a declared licence's text actually is, as component properties.

    CycloneDX 1.5 has no field that says "the text of this licence is that
    file", and inventing one would make the document describe itself rather
    than the release.  `properties` is the schema's own extension point for
    facts about a component that the fixed vocabulary does not cover, and it
    is what a consumer already reads when it wants the rest.
    """
    return [
        {"name": "wtop:licence-text:path", "value": record["path"]},
        {"name": "wtop:licence-text:sha256", "value": record["sha256"]},
        {"name": "wtop:licence-text:present-in", "value": ",".join(record["present_in"])},
        {"name": "wtop:licence-text:covers", "value": record["covers"]},
    ]


def notice_sentence(record: typing.Dict) -> str:
    """One clause for a component description, saying where its terms are."""
    if len(record["present_in"]) > 1:
        return (" The text of those terms is carried by the release as %s, and "
                "the onefile holds the same bytes." % record["path"])
    return (" The text of those terms is carried by the release as %s; the "
            "onefile does not hold a copy, so a distributor redistributing "
            "that form has to carry the text forward themselves." % record["path"])



def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--onedir", type=pathlib.Path,
                        default=pathlib.Path("dist/wtop"),
                        help="the onedir bundle directory")
    parser.add_argument("--onefile", type=pathlib.Path,
                        default=pathlib.Path("dist/wtop-onefile"),
                        help="the single-file bundle")
    parser.add_argument("--output", type=pathlib.Path,
                        default=pathlib.Path("dist/SBOM.cyclonedx.json"),
                        help="where to write the SBOM")
    arguments = parser.parse_args()

    root = pathlib.Path(__file__).resolve().parent.parent
    revision = git_revision(root) or declared_version(root)

    candidates = {
        "launcher": arguments.onedir / "wtop",
        "onefile": arguments.onefile,
        "module": arguments.onedir / ".luai" / "native" / "wtop_native.so",
    }

    missing = sorted(name for name, path in candidates.items() if not path.is_file())
    if missing:
        # Named specifically, so that "run make bundle-dir and make bundle-file
        # first" is what a reader is told rather than "something went wrong".
        print("wtop: refusing to write an SBOM that describes nothing.", file=sys.stderr)
        for name in missing:
            print("  missing %s: %s" % (name, candidates[name]), file=sys.stderr)
        print("  build the release artifacts first: make bundle-dir bundle-file",
              file=sys.stderr)
        return 1

    hashes = {name: file_hash(path) for name, path in candidates.items()}
    verbatim = embeds_verbatim(candidates["onefile"], candidates["module"])

    # Every licence this document is about to declare has to have its text in
    # the release.  The check runs before a single component is built, so a
    # document that would name terms it does not carry is never written at all
    # -- the same refusal the missing-artifact check above makes, for the same
    # reason: the file on disk is what a distributor reads, and a document that
    # exists is taken as a statement about the release.
    licences = {}
    without_text = []
    for licence_id, relative, covers in LICENCE_TEXTS:
        path = arguments.onedir / relative
        if not path.is_file():
            without_text.append((licence_id, path))
            continue
        present_in = ["onedir"]
        if embeds_verbatim(candidates["onefile"], path):
            present_in.append("onefile")
        licences[licence_id] = {
            "path": relative,
            "sha256": file_hash(path),
            "present_in": present_in,
            "covers": covers,
        }
    if without_text:
        print("wtop: refusing to write an SBOM that declares licences the release "
              "does not carry.", file=sys.stderr)
        for licence_id, path in without_text:
            print("  no text for %s: %s" % (licence_id, path), file=sys.stderr)
        print("  the bundle is built without it: check that make bundle-dir still "
              "copies $(RELEASE_LICENCE) and that the packaging tool still ships "
              "its own licence texts", file=sys.stderr)
        return 1

    def h(name):
        return [{"alg": "SHA-256", "content": hashes[name]}]

    launcher_ref = "wtop@%s" % revision
    module_ref = "wtop_native@%s" % revision
    lua_ref = "lua@%s" % LUA_VERSION

    if verbatim:
        module_note = (
            "The onefile carries these same bytes rather than a copy rebuilt "
            "from the same source, so the onefile's own hash already covers "
            "this module and a second hash would be the same number twice "
            "instead of another fact."
        )
    else:
        module_note = (
            "The onefile does not carry these bytes -- it holds a different "
            "build of the same sources -- so the hash below is the only one "
            "this document can offer for what the onedir bundle ships."
        )

    components = [
        component(launcher_ref, "wtop", revision, "EUPL-1.2",
                  "WaterRun's top -- a deep observability TUI. The onedir entry "
                  "point and the onefile entry point are both this component; "
                  "the two hashes are the two files it ships as."
                  + notice_sentence(licences["EUPL-1.2"]),
                  kind="application", hashes=h("launcher") + h("onefile"),
                  properties=licence_properties(licences["EUPL-1.2"])),
        component(module_ref, "wtop_native", revision, "EUPL-1.2",
                  "Native module compiled from this project's C sources and "
                  "shipped as a file in the onedir bundle. " + module_note
                  + notice_sentence(licences["EUPL-1.2"]),
                  hashes=h("module"),
                  properties=licence_properties(licences["EUPL-1.2"])),
        component(lua_ref, "lua", LUA_VERSION, "MIT",
                  "PUC Lua runtime. It is linked into the onedir launcher, whose "
                  "measured glibc floor is the interpreter's, and carried as a "
                  "separate ELF image inside the onefile. The release ships no "
                  "standalone Lua file to hash; tools/elf_floors.py measures the "
                  "runtime inside both artifacts instead."
                  + notice_sentence(licences["MIT"]),
                  properties=licence_properties(licences["MIT"])),
        component("luainstaller@%s" % LUAINSTALLER_VERSION, "luainstaller",
                  LUAINSTALLER_VERSION, "LGPL-3.0-or-later",
                  "Build-time packaging tool; not present in the produced "
                  "executables, and it ships its own terms inside the bundle."
                  + notice_sentence(licences["LGPL-3.0-or-later"]),
                  scope="excluded",
                  properties=licence_properties(licences["LGPL-3.0-or-later"])),
    ]

    document = {
        "bomFormat": "CycloneDX",
        "specVersion": "1.5",
        "serialNumber": "urn:uuid:%s" % uuid.uuid5(
            uuid.NAMESPACE_URL, "wtop-sbom-%s" % revision),
        "version": 1,
        "metadata": {
            "component": {
                "bom-ref": launcher_ref,
                "type": "application",
                "name": "wtop",
                "version": revision,
                "licenses": [{"license": {"id": "EUPL-1.2"}}],
            },
        },
        "components": components,
        "dependencies": [
            {"ref": launcher_ref, "dependsOn": [module_ref, lua_ref]},
            {"ref": module_ref, "dependsOn": []},
            {"ref": lua_ref, "dependsOn": []},
        ],
    }
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(
        json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print("wtop: SBOM written to %s (%s), %d artifacts hashed, %d licence texts "
          "located (%d of them also inside the onefile)"
          % (arguments.output, revision, len(hashes), len(licences),
             sum(1 for r in licences.values() if len(r["present_in"]) > 1)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
