#!/bin/sh
# Writes src/wtop/build_id.lua with the current git revision. Deterministic:
# no timestamps, so identical trees produce identical bundles. A tree without
# git metadata produces no file and the version stays revision-less.
set -eu

project_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
target="$project_dir/src/wtop/build_id.lua"

revision=$(git -C "$project_dir" describe --always --dirty --tags 2>/dev/null || true)
if [ -z "$revision" ]; then
    rm -f "$target"
    exit 0
fi

printf -- '-- Generated by tools/write_build_id.sh; DO NOT EDIT.\nreturn { revision = "%s" }\n' \
    "$revision" > "$target"
