#!/bin/sh
# Writes the build identity and the version: the revision and the version for the
# Lua tree, and the matching header for the C module.  Deterministic: no
# timestamps, so identical trees produce identical bundles.  A tree without git
# metadata produces no Lua revision module and leaves the header saying so, and
# the revision stays empty; the version is not derived from git and is always
# written.
#
# Both facts come out of one reading of one place, and that is the whole point of
# routing the C side through a generated header rather than a -D flag: the module
# and the Lua tree must be able to be compared, and two independent readings
# could disagree between the moment one side is built and the moment the other
# is.  Comparing them would be comparing noise.
#
# The version used to be three literals -- one here, one in version.lua, one in
# the C source -- and two of the three surfaces a user can run printed the
# result.  A bump that missed the C copy made `--diagnose` state two different
# versions in the same report, with nothing flagging it, which is the same shape
# as the release tools that asserted conclusions they had not measured.  VERSION
# at the top of the tree is now the only place a human edits, and the three
# consumers are outputs of this script.
set -eu

project_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
target="$project_dir/src/wtop/build_id.lua"
version_target="$project_dir/src/wtop/version.lua"
header_dir="$project_dir/build/native"
header="$header_dir/build_revision.h"
version_header="$header_dir/build_version.h"
version_file="$project_dir/VERSION"

revision=$(git -C "$project_dir" describe --always --dirty --tags 2>/dev/null || true)

# Read with a shell builtin rather than by parsing Lua: version.lua is generated
# *from* this file, so a parser for it would be reading its own output back, and
# a reformatting of the generated module could not break the build only if the
# format were the contract.  A VERSION file with anything unexpected in it is a
# hard error instead, because a version that is silently something else is worse
# than a build that stops.
[ -f "$version_file" ] || {
    echo "$0: $version_file is missing; it is the only place the version is written" >&2
    exit 1
}
version=$(tr -d ' \t\r\n' < "$version_file")
case ${version:-} in
    ''|*[!0-9A-Za-z.+-]*)
        echo "$0: VERSION must hold one version string, got: $(cat "$version_file")" >&2
        exit 1
        ;;
esac

mkdir -p "$header_dir" "$project_dir/src/wtop"
if [ -z "$revision" ]; then
    # A tree with no git metadata has no revision to report, and inventing one
    # would be worse than saying so.  The header still has to exist, because the
    # module includes it unconditionally; the value makes the absence
    # visible at runtime instead of turning into a stale identity.
    rm -f "$target"
    printf -- '/* Generated by tools/write_build_id.sh; DO NOT EDIT. */\n#define WTOP_BUILD_REVISION ""\n' \
        > "$header"
else
    printf -- '-- Generated by tools/write_build_id.sh; DO NOT EDIT.\nreturn { revision = "%s" }\n' \
        "$revision" > "$target"
    printf -- '/* Generated by tools/write_build_id.sh; DO NOT EDIT. */\n#define WTOP_BUILD_REVISION "%s"\n' \
        "$revision" > "$header"
fi

# The version is written on every run, including a tree with no git: it does not
# come from git, so the absence of a revision is no reason for the program to be
# unable to say which version it is.
printf -- '/* Generated by tools/write_build_id.sh; DO NOT EDIT. */\n#define WTOP_VERSION "%s"\n' \
    "$version" > "$version_header"
cat > "$version_target" <<LUA_EOF
-- Generated by tools/write_build_id.sh from VERSION; DO NOT EDIT.
-- The revision is optional: a tree without git metadata has none to report, and
-- inventing one would be worse than saying so.
local ok, build_id = pcall(require, "wtop.build_id")

return {
    name = "wtop",
    version = "$version",
    revision = ok and type(build_id) == "table" and build_id.revision or nil,
    description = "WaterRun's top — a deep Linux observability TUI",
}
LUA_EOF
